# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: openapi
#   annotations:
#     github.com/project-slug: caiotaavares/openapi
# spec:
#   type: other
#   lifecycle: unknown
#   owner: guests

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: academico
  description: |
    API de integração do sistema Acadêmico.
    - Dev: https://api.dev.unesp.br/academico/api/*
    - Prod: https://api.app.unesp.br/academico/api/*
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: https://api.homolog.unesp.br/paades-api/publico/swagger-ui/index.html
